# Default configuration for m68k-softmmu

CONFIG_COLDFIRE=y
//CONFIG_GDBSTUB_XML=y
CONFIG_PTIMER=y
CONFIG_ESCC=y
CONFIG_FRAMEBUFFER=y
CONFIG_ADB=y
CONFIG_MAC_VIA=y
CONFIG_ESP=y
CONFIG_ASC=y
CONFIG_MACFB=y
CONFIG_NUBUS=y
